apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005
  selector:
    app: kims-convenience
    tier: backend
    type: cart

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  template:
    metadata:
      name: cart-pod
      labels:
        app: kims-convenience
        tier: backend
        type: cart
    spec:
      containers:
        - name: cart-container
          image: anshikam/kims-convenience-cart
          env:
            - name: MYSQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-user-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-user-password
            - name: DOCKER_INTERNAL
              valueFrom:
                configMapKeyRef:
                  name: cart-configmap
                  key: docker-internal-url
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: cart-configmap
                  key: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kims-convenience
      tier: backend
      type: cart
