apiVersion: v1
kind: Service
metadata:
  name: kc-cart-service
  labels:
    app: kims-convenience
    tier: backend
    type: kc-cart
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005
  selector:
    app: kims-convenience
    tier: backend
    type: kc-cart

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-cart-deployment
  labels:
    app: kims-convenience
    tier: backend
    type: kc-cart
spec:
  template:
    metadata:
      name: kc-cart-pod
      labels:
        app: kims-convenience
        tier: backend
        type: kc-cart
    spec:
      containers:
        - name: kc-cart
          image: anshikam/kims-convenience-cart
          env:
            - name: MYSQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kc-cart-mysql-configmap
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: kc-cart-mysql-configmap
                  key: mysql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kc-cart-mysql-configmap
                  key: mysql-user-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-cart-mysql-secret
                  key: mysql-user-password
            - name: DOCKER_INTERNAL
              valueFrom:
                configMapKeyRef:
                  name: kc-cart-configmap
                  key: docker-internal-url
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kc-cart-configmap
                  key: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kims-convenience
      tier: backend
      type: kc-cart
